### ISSUE TITLE
SDK-Scheme-Adapter build fails when upgrading NX dependency from 16.5.0 to 16.10.0

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#3586]
**Summary**:

SDK-Scheme-Adapter build fails when upgrading NX dependency from 16.5.0 to 16.10.0 showing the following error:

 ``logs
  >  NX   Running target build for 8 projects
  
     ✖  nx run @mojaloop/sdk-scheme-adapter-outbound-domain-event-handler:build
        src/api-server/app.ts(33,52): error TS2307: Cannot find module '@mojaloop/sdk-scheme-adapter-private-shared-lib' or its corresponding type declarations.
        src/api-server/index.ts(30,52): error TS2307: Cannot find module '@mojaloop/sdk-scheme-adapter-private-shared-lib' or its corresponding type declarations.
        src/application/handler.ts(50,8): error TS2307: Cannot find module '@mojaloop/sdk-scheme-adapter-private-shared-lib' or its corresponding type declarations.
        src/application/handlers/bulk-quotes-callback-received.ts(4,8): error TS2307: Cannot find module '@mojaloop/sdk-scheme-adapter-private-shared-lib' or its corresponding type declarations.
        src/application/handlers/bulk-quotes-callback-received.ts(6,49): error TS2307: Cannot find module '@mojaloop/sdk-scheme-adapter-private-shared-lib' or its corresponding type declarations.
        src/application/handlers/bulk_transfers_callback_received.ts(7,8): error TS2307: Cannot find module '@mojaloop/sdk-scheme-adapter-private-shared-lib' or its corresponding type declarations.
        src/application/handlers/bulk_transfers_processed.ts(4,8): error TS2307: Cannot find module '@mojaloop/sdk-scheme-adapter-private-shared-lib' or its corresponding type declarations.
        src/application/handlers/party-info-callback-received.ts(4,8): error TS2307: Cannot find module '@mojaloop/sdk-scheme-adapter-private-shared-lib' or its corresponding type declarations.
        src/application/handlers/party-info-callback-received.ts(6,48): error TS2307: Cannot find module '@mojaloop/sdk-scheme-adapter-private-shared-lib' or its corresponding type declarations.
        src/application/handlers/sdk-outbound-bulk-party-info-requested.ts(30,8): error TS2307: Cannot find module '@mojaloop/sdk-scheme-adapter-private-shared-lib' or its corresponding type declarations.
        src/application/handlers/sdk-outbound-bulk-party-info-requested.ts(32,56): error TS2307: Cannot find module '@mojaloop/sdk-scheme-adapter-private-shared-lib' or its corresponding type declarations.
        src/application/handlers/sdk-outbound-bulk-request-received.ts(28,108): error TS2307: Cannot find module '@mojaloop/sdk-scheme-adapter-private-shared-lib' or its corresponding type declarations.
        src/application/handlers/sdk-outbound-bulk-request-received.ts(30,53): error TS2307: Cannot find module '@mojaloop/sdk-scheme-adapter-private-shared-lib' or its corresponding type declarations.
        src/application/handlers/sdk_outbound_bulk_accept_party_info_processed.ts(28,120): error TS2307: Cannot find module '@mojaloop/sdk-scheme-adapter-private-shared-lib' or its corresponding type declarations.
        src/application/handlers/sdk_outbound_bulk_accept_party_info_processed.ts(30,62): error TS2307: Cannot find module '@mojaloop/sdk-scheme-adapter-private-shared-lib' or its corresponding type declarations.
        src/application/handlers/sdk_outbound_bulk_accept_party_info_received.ts(28,124): error TS2307: Cannot find module '@mojaloop/sdk-scheme-adapter-private-shared-lib' or its corresponding type declarations.
        src/application/handlers/sdk_outbound_bulk_accept_party_info_received.ts(30,61): error TS2307: Cannot find module '@mojaloop/sdk-scheme-adapter-private-shared-lib' or its corresponding type declarations.
        src/application/handlers/sdk_outbound_bulk_accept_quote_processed.ts(29,168): error TS2307: Cannot find module '@mojaloop/sdk-scheme-adapter-private-shared-lib' or its corresponding type declarations.
        src/application/handlers/sdk_outbound_bulk_accept_quote_received.ts(28,157): error TS2307: Cannot find module '@mojaloop/sdk-scheme-adapter-private-shared-lib' or its corresponding type declarations.
        src/application/handlers/sdk_outbound_bulk_response_sent.ts(7,8): error TS2307: Cannot find module '@mojaloop/sdk-scheme-adapter-private-shared-lib' or its corresponding type declarations.
        src/application/handlers/sdk_outbound_bulk_transfers_request_processed.ts(7,8): error TS2307: Cannot find module '@mojaloop/sdk-scheme-adapter-private-shared-lib' or its corresponding type declarations.
        src/application/index.ts(33,110): error TS2307: Cannot find module '@mojaloop/sdk-scheme-adapter-private-shared-lib' or its corresponding type declarations.
        src/shared/config.ts(18,72): error TS2307: Cannot find module '@mojaloop/sdk-scheme-adapter-private-shared-lib' or its corresponding type declarations.
        src/types/domain_event_handler_options.ts(26,75): error TS2307: Cannot find module '@mojaloop/sdk-scheme-adapter-private-shared-lib' or its corresponding type declarations.
``|

This cause several CI pipelines to fail: https://app.circleci.com/pipelines/github/mojaloop/sdk-scheme-adapter/2948/workflows/8e7f083b-19a3-4286-954d-167183f78da9

**Severity**:
(Low, Medium, High)

**Priority**:
(Critical, Medium, Low)

**Expected Behavior**

**Steps to Reproduce**
  1.
  2.
  3.

**Specifications**
  - Component (if known):
  - Version:
  - Platform:
  - Subsystem:
  - Type of testing:
  - Bug found/raised by:

**Notes**:

- Severity when opened:
- Priority when opened:

**Comment by gibaros** [comment]
Fixed at: https://github.com/mojaloop/sdk-scheme-adapter/pull/681 by migrating to Yarn4
