### ISSUE TITLE
ALS Unit Test break when updating central-services-health from 10.6.0 to 11.0.0

### ISSUE THREAD

**Issue by gibaros** [mojaloop/project#1987]
**Summary**:
ALS Unit Test break when updating central-services-health from 10.6.0 to 11.0.0.

Specifically, the following error is seen when running unit tests:

Cannot find module '@hapi/joi' from 'node_modules/@now-ims/hapi-now-auth/lib/index.js'

**Severity**:
Low

**Priority**:
Low

**Expected Behavior**
Unit tests should not break when updating dependencies, or more specifically hapi/joi module should still be accessible after updating dependnecy.

**Steps to Reproduce**
  1.update central-services-health from 10.6.0 to 11.0.0
  2.npm install
  3.npm run test:unit

**Specifications**
  - Component (if known): ALS
  - Version: 11.1.7
  - Platform:
  - Subsystem:
  - Type of testing: Unit Test
  - Bug found/raised by: Juan Correa

**PR**:
- [ ] https://github.com/mojaloop/account-lookup-service/pull/396

**Notes**:

- Severity when opened: Low
- Priority when opened: Low
